{
 "title": "GPU",
 "tags": [ "GPU" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(dcgm_gpu_temp{job=\"nvidia-dcgm-exporter\"}, instance)"
   },
   {
    "name": "uuid",
    "query": "label_values(dcgm_gpu_temp{instance=\"$instance\"}, uuid)"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "dcgm_gpu_temp{instance=\"$instance\",uuid=\"$uuid\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Avg Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "avg(dcgm_gpu_temp{instance=\"$instance\",uuid=\"$uuid\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "dcgm_power_usage{instance=\"$instance\",uuid=\"$uuid\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "sum(dcgm_power_usage{instance=\"$instance\",uuid=\"$uuid\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "dcgm_sm_clock{instance=\"$instance\",uuid=\"$uuid\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Clocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "dcgm_memory_clock{instance=\"$instance\",uuid=\"$uuid\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilizations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "dcgm_gpu_utilization{instance=\"$instance\",uuid=\"$uuid\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Mem Copy Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "dcgm_mem_copy_utilization{instance=\"$instance\",uuid=\"$uuid\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Frame Buffer Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "dcgm_fb_used{instance=\"$instance\",uuid=\"$uuid\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "dcgm_fb_free{instance=\"$instance\",uuid=\"$uuid\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  }
 ]
}